version: '3'

services:
  php:
    build: ./docker/php
    volumes:
      - ./:/app
    working_dir: /app
    user: '1000:1000'
    ports:
      - 8000:8000
    networks:
      - bridge
    command: php -S 0.0.0.0:8000 -t /app

volumes:
  dbdata:

networks: #Привязка адреса контейнерам 
  bridge:
    driver: bridge
    ipam:
     config:
       - subnet: 172.10.1.0/24
         gateway: 172.10.1.1
         aux_addresses:
           php: 172.10.1.10